const districts = [
    {
        id: "bagalkote",
        name: "Bagalkote",
        spot: "Badami Cave Temples & Pattadakal",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "Ancient Badami rock-cut cave temples and UNESCO World Heritage monument complex at Pattadakal.",
        overview: "Bagalkote was the center of Badami Chalukya dynasty architecture during the 6th to 8th centuries.",
        season: "October to March",
        timings: "9:00 AM - 5:30 PM",
        fee: "₹25 (Indians), ₹300 (Foreigners)",
        attractions: ["Badami Cave Temples", "Pattadakal UNESCO Complex", "Aihole Temple Architecture", "Banashankari Amma Temple"],
        reach: "Nearest Airport: Hubballi (105 km). Connected via Badami Railway Station.",
        food: "Jolada Rotti, Shenga Chutney, Badami Pedha",
        map: "https://maps.google.com/?q=Badami+Cave+Temples"
    },
    {
        id: "ballari",
        name: "Ballari",
        spot: "Ballari Fort & Sandur Hills",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80",
        shortDesc: "Historic hill fort built on a monolithic rock face and mineral-rich forest ranges of Sandur.",
        overview: "Ballari Fort dominates the skyline from atop Fort Hill.",
        season: "October to February",
        timings: "8:00 AM - 6:00 PM",
        fee: "Free",
        attractions: ["Ballari Fort Monolith", "Sandur Kumaraswamy Temple", "Mincheri Hill Viewpoint"],
        reach: "Nearest Airport: Jindal Vijaynagar (40 km). Connected via Ballari Junction Railway Station.",
        food: "Jowar Rotti, Uggani Mirchi Bajji",
        map: "https://maps.google.com/?q=Ballari+Fort"
    },
    {
        id: "belagavi",
        name: "Belagavi (Belgaum)",
        spot: "Gokak Falls & Belagavi Fort",
        region: "North Interior",
        category: "Nature",
        image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
        shortDesc: "Picturesque waterfalls echoing Niagara Falls, historic forts, and cool Western Ghat foothills.",
        overview: "Belagavi borders Maharashtra and Goa, featuring the horseshoe-shaped Gokak Falls.",
        season: "July to January",
        timings: "8:00 AM - 6:00 PM",
        fee: "Free (₹20 vehicle parking)",
        attractions: ["Gokak Falls Hanging Bridge", "Belagavi Fort & Kamal Basti", "Kittur Fort Ruins"],
        reach: "Connected via Belagavi Airport (IXG) and Belagavi Railway Station.",
        food: "Kunda Sweet, Sol Kadi, Belagavi Butter Dosa",
        map: "https://maps.google.com/?q=Gokak+Falls"
    },
    {
        id: "bengaluru-urban",
        name: "Bengaluru Urban",
        spot: "Bengaluru Palace & Lalbagh",
        region: "South Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The Silicon Valley of India, blending Tudor-style architecture with botanical heritage.",
        overview: "Bengaluru features iconic landmarks like Bengaluru Palace, Lalbagh Glasshouse, and Cubbon Park.",
        season: "Year-Round",
        timings: "10:00 AM - 5:30 PM",
        fee: "Palace: ₹240",
        attractions: ["Bengaluru Palace", "Lalbagh Glasshouse", "Cubbon Park", "ISKCON Temple"],
        reach: "Kempegowda Int'l Airport (BLR) / KSR Bengaluru Railway Station.",
        food: "Benne Dosa, Filter Coffee, Mysore Pak",
        map: "https://maps.google.com/?q=Bangalore+Palace"
    },
    {
        id: "chikkamagaluru",
        name: "Chikkamagaluru",
        spot: "Mullayanagiri & Baba Budangiri",
        region: "Malnad",
        category: "Nature",
        image: "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The birthplace of coffee in India, offering peak trekking, coffee estate stays, and mountain air.",
        overview: "Chikkamagaluru sits at the foothills of the Mullayanagiri range—the highest peak in Karnataka.",
        season: "September to March",
        timings: "Open all day",
        fee: "Free",
        attractions: ["Mullayanagiri Peak", "Baba Budangiri", "Hebbe Falls", "Kudremukh National Park"],
        reach: "Nearest Airport: Mangalore (150 km). Road access from Bengaluru (240 km).",
        food: "Malanadu Meals, Fresh Filter Coffee",
        map: "https://maps.google.com/?q=Mullayanagiri"
    },
    {
        id: "dakshina-kannada",
        name: "Dakshina Kannada (Mangaluru)",
        spot: "Panambur Beach & Kadri Temple",
        region: "Coastal",
        category: "Beach",
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
        shortDesc: "Coastal hub famous for golden sand beaches, ancient temples, and coastal seafood.",
        overview: "Headquartered at Mangaluru, Dakshina Kannada blends Arabian Sea coastline with heritage shrines.",
        season: "October to March",
        timings: "Beaches open all day",
        fee: "Free",
        attractions: ["Panambur Beach", "Tannirbhavi Beach", "Kadri Manjunatha Temple"],
        reach: "Mangaluru Int'l Airport (IXE) / Mangaluru Central Railway Station.",
        food: "Mangalore Fish Curry, Kori Rotti, Neer Dosa",
        map: "https://maps.google.com/?q=Panambur+Beach"
    },
    {
        id: "hassan",
        name: "Hassan",
        spot: "Belur, Halebeedu & Shravanabelagola",
        region: "South Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1621252179027-94459d278660?auto=format&fit=crop&w=800&q=80",
        shortDesc: "Home to intricate Hoysala stone carvings and 57-foot tall monolithic Gommateshwara statue.",
        overview: "Hassan contains UNESCO-nominated Hoysala architecture at Belur Chennakeshava Temple and Halebeedu.",
        season: "October to March",
        timings: "7:30 AM - 7:30 PM",
        fee: "Free",
        attractions: ["Chennakeshava Temple Belur", "Hoysaleswara Temple Halebeedu", "Shravanabelagola Monolith"],
        reach: "Nearest Airport: Bengaluru (180 km). Connected via Hassan Junction Rail.",
        food: "Ragi Mudde with Soppu Saaru, Akki Roti",
        map: "https://maps.google.com/?q=Belur+Temple"
    },
    {
        id: "kodagu",
        name: "Kodagu (Coorg)",
        spot: "Abbey Falls & Raja's Seat",
        region: "Malnad",
        category: "Nature",
        image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80",
        shortDesc: "Famous hill town with coffee plantations, misty hills, lush greenery, and Kodava culture.",
        overview: "Kodagu is a tranquil hill destination on the Western Ghats offering coffee estates and waterfalls.",
        season: "September to June",
        timings: "9:00 AM - 5:00 PM",
        fee: "₹15 - ₹50",
        attractions: ["Abbey Falls", "Raja's Seat Viewpoint", "Dubare Elephant Camp"],
        reach: "Nearest Airport: Kannur (90 km) / Mangalore (140 km).",
        food: "Pandi Curry, Akki Oti, Kadambuttu",
        map: "https://maps.google.com/?q=Madikeri+Coorg"
    },
    {
        id: "mysuru",
        name: "Mysuru (Mysore)",
        spot: "Mysore Palace & Chamundi Hill",
        region: "South Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1600100397608-f09070624022?auto=format&fit=crop&w=800&q=80",
        shortDesc: "Cultural capital of Karnataka, famous for Mysore Palace, royal heritage, and Dasara.",
        overview: "Mysuru is world-famous for its royal architecture, silk sarees, and sandalwood.",
        season: "October to March",
        timings: "10:00 AM - 5:30 PM",
        fee: "₹100 (Indians), ₹300 (Foreigners)",
        attractions: ["Grand Mysore Palace", "Chamundeshwari Temple", "Brindavan Gardens", "Mysore Zoo"],
        reach: "Mysore Airport (MYQ) / Mysuru Junction Railway Station.",
        food: "Mysore Pak, Mysore Masala Dosa",
        map: "https://maps.google.com/?q=Mysore+Palace"
    },
    {
        id: "shivamogga",
        name: "Shivamogga (Shimoga)",
        spot: "Jog Falls & Agumbe Rainforest",
        region: "Malnad",
        category: "Nature",
        image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
        shortDesc: "Gateway to Western Ghats, featuring 253-meter Jog Falls and Agumbe rainforest sunset.",
        overview: "Shivamogga is blessed with cascading rivers and forests, including the 253m Jog Falls.",
        season: "July to December",
        timings: "6:00 AM - 6:00 PM",
        fee: "₹15 Entry Fee",
        attractions: ["Jog Waterfalls", "Agumbe Sunset Point", "Sakrebyle Elephant Camp"],
        reach: "Shivamogga Airport (RQY) / Shivamogga Town Railway Station.",
        food: "Malanadu Thali, Midigayi Pickles",
        map: "https://maps.google.com/?q=Jog+Falls"
    },
    {
        id: "udupi",
        name: "Udupi",
        spot: "St. Mary's Island & Krishna Matha",
        region: "Coastal",
        category: "Beach",
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
        shortDesc: "Hexagonal basaltic rock columns at St. Mary's Island, beaches, and Krishna Temple.",
        overview: "Udupi offers coastal beauty and spiritual heritage, including unique basalt formations.",
        season: "October to March",
        timings: "Ferry: 9:00 AM - 5:00 PM",
        fee: "Ferry: ₹400",
        attractions: ["St. Mary's Basalt Island", "Malpe Sea Walk Beach", "Udupi Sri Krishna Temple"],
        reach: "Nearest Airport: Mangaluru (60 km). Connected via Udupi Rail.",
        food: "Udupi Masala Dosa, Gadbad Ice Cream, Neer Dosa",
        map: "https://maps.google.com/?q=St+Marys+Island+Udupi"
    },
    {
        id: "vijayanagara",
        name: "Vijayanagara",
        spot: "Hampi Monument Group",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "UNESCO World Heritage site featuring ancient ruins of Vijayanagara Empire.",
        overview: "Hampi was the capital of Vijayanagara Empire in the 14th century, containing grand temples and stone chariots.",
        season: "November to February",
        timings: "8:30 AM - 5:30 PM",
        fee: "₹40 (Indians), ₹600 (Foreigners)",
        attractions: ["Stone Chariot at Vittala Temple", "Virupaksha Temple", "Lotus Mahal"],
        reach: "Nearest Rail: Hospet Junction (13 km). Airport: Jindal Vijaynagar (35 km).",
        food: "South Indian Thali, Fresh Coconut Water",
        map: "https://maps.google.com/?q=Hampi+Karnataka"
    }
];