const districts = [
    {
        id: "bagalkote",
        name: "Bagalkote",
        spot: "Badami Cave Temples & Pattadakal",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The cradle of Indian temple architecture featuring ancient sandstone rock-cut caves and UNESCO World Heritage monuments.",
        overview: "Bagalkote district served as the capital of the Early Chalukya dynasty (540–757 CE). The region is world-renowned for Badami's four monolithic rock-cut cave temples carved directly into red sandstone cliffs overlooking the Agastya Lake.",
        season: "October to March",
        timings: "9:00 AM - 5:30 PM",
        fee: "₹25 for Indians, ₹300 for Foreigners",
        attractions: ["Badami Sandstone Cave Temples", "Pattadakal UNESCO Group of Monuments", "Aihole Archaeological Complex", "Agastya Tirtha Lake"],
        reach: "Nearest Airport: Hubballi Airport (~105 km). Rail: Badami Railway Station.",
        food: "Jolada Rotti, Shenga Chutney, Badanekayi Yennegai, and Badami Pedha.",
        map: "https://maps.google.com/?q=Badami+Cave+Temples"
    },
    {
        id: "ballari",
        name: "Ballari (Bellary)",
        spot: "Ballari Fort Monolith & Sandur Valley",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80",
        shortDesc: "A historic fortress city anchored by a massive granite monolith hill fort and the lush, mineral-rich Sandur valley.",
        overview: "Ballari district is distinguished by the majestic Ballari Fort, constructed atop the 'Ballari Gudda'—a sprawling single-rock monolith.",
        season: "October to February",
        timings: "8:00 AM - 6:00 PM",
        fee: "Free entry",
        attractions: ["Ballari Fort Citadel", "Sandur Kumaraswamy Temple", "Mincheri Hill Viewpoint"],
        reach: "Nearest Airport: Jindal Vijaynagar Airport (~40 km). Rail: Ballari Junction.",
        food: "Jowar Rotti Meals, Uggani with Spicy Mirchi Bajji.",
        map: "https://maps.google.com/?q=Ballari+Fort"
    },
    {
        id: "belagavi",
        name: "Belagavi (Belgaum)",
        spot: "Gokak Falls & Belagavi Fort",
        region: "North Interior",
        category: "Nature",
        image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The second capital of Karnataka, featuring horseshoe waterfalls, historic forts, and Western Ghat foothills.",
        overview: "Belagavi lies along the Western Ghats. The district is celebrated for Gokak Falls, where the Ghataprabha River plunges 52 meters down a sandstone cliff.",
        season: "July to January",
        timings: "8:00 AM - 6:00 PM",
        fee: "Free",
        attractions: ["Gokak Falls & Suspension Bridge", "Belagavi Fort & Kamal Basti", "Kittur Fort"],
        reach: "Airport: Belagavi Airport. Rail: Belagavi Railway Station.",
        food: "Belagavi Kunda, Mandige, Sol Kadi, and Butter Dosa.",
        map: "https://maps.google.com/?q=Gokak+Falls"
    },
    {
        id: "bengaluru-rural",
        name: "Bengaluru Rural",
        spot: "Ghati Subramanya & Devanahalli Fort",
        region: "South Interior",
        category: "Pilgrimage",
        image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80",
        shortDesc: "A serene getaway surrounding the state capital, offering trekking peaks, silk production hubs, and ancient shrines.",
        overview: "Encircling the capital city, Bengaluru Rural blends rural landscapes with rich historic heritage like Devanahalli Fort and Ghati Subramanya.",
        season: "September to March",
        timings: "6:00 AM - 8:30 PM",
        fee: "Free Entry",
        attractions: ["Ghati Subramanya Temple", "Devanahalli Fort", "Makalidurga Fort Trek"],
        reach: "Airport: Kempegowda International Airport. Rail: Doddaballapura Station.",
        food: "Ragi Mudde with Avarekalu Saaru, Akki Roti.",
        map: "https://maps.google.com/?q=Ghati+Subramanya+Temple"
    },
    {
        id: "bengaluru-urban",
        name: "Bengaluru Urban",
        spot: "Bengaluru Palace, Lalbagh & Cubbon Park",
        region: "South Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The Silicon Valley of Asia, seamlessly blending 19th-century royal palaces with urban greenery and tech hubs.",
        overview: "Bengaluru Urban is the capital city of Karnataka. Major highlights include Bengaluru Palace, Lalbagh Botanical Garden, and Cubbon Park.",
        season: "Year-Round",
        timings: "10:00 AM - 5:30 PM",
        fee: "Palace: ₹240",
        attractions: ["Bengaluru Palace", "Lalbagh Botanical Garden", "Vidhana Soudha", "Cubbon Park", "ISKCON Temple"],
        reach: "Airport: Kempegowda Int'l Airport. Metro: Namma Metro.",
        food: "Crispy Benne Masala Dosa, Filter Coffee, Mysore Pak.",
        map: "https://maps.google.com/?q=Bangalore+Palace"
    },
    {
        id: "bidar",
        name: "Bidar",
        spot: "Bidar Fort & Bahmani Sultanate Tombs",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "Karnataka's northern crown, packed with medieval Islamic architecture, Bahmani forts, and Bidriware metal craft.",
        overview: "Bidar served as the capital of the Bahmani Kingdom. The massive Bidar Fort complex features Rangeen Mahal and Solah Khamba Mosque.",
        season: "October to March",
        timings: "9:00 AM - 5:00 PM",
        fee: "Free Entry",
        attractions: ["Bidar Fort Complex", "Mahmud Gawan Madrasa", "Gurudwara Nanak Jhira Sahib"],
        reach: "Airport: Bidar Airport / Kalaburagi Airport. Rail: Bidar Railway Station.",
        food: "Naan Qalia, Bidri Mutton Biryani, Tahari.",
        map: "https://maps.google.com/?q=Bidar+Fort"
    },
    {
        id: "chamarajanagar",
        name: "Chamarajanagar",
        spot: "Bandipur National Park & BR Hills",
        region: "South Interior",
        category: "Wildlife",
        image: "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=800&q=80",
        shortDesc: "A wilderness haven featuring tiger reserves, dense elephant corridors, and sacred mountain ranges.",
        overview: "Chamarajanagar shelters Bandipur National Park and Biligirirangana Hills (BR Hills) Wildlife Sanctuary.",
        season: "October to May",
        timings: "Safari: 6:00 AM & 3:00 PM",
        fee: "Safari: ₹350 - ₹1500",
        attractions: ["Bandipur Tiger Reserve", "BR Hills Sanctuary", "Male Mahadeshwara Betta"],
        reach: "Airport: Mysore Airport (~70 km). Road: Mysuru-Ooty Highway.",
        food: "Banana Leaf Thali, Naati Koli Saaru, Wild Forest Honey.",
        map: "https://maps.google.com/?q=Bandipur+National+Park"
    },
    {
        id: "chikkaballapura",
        name: "Chikkaballapura",
        spot: "Nandi Hills & Bhoga Nandeeshwara Temple",
        region: "South Interior",
        category: "Nature",
        image: "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80",
        shortDesc: "Famous hill station for cloud-sea sunrises, adventure night treks, and ancient Dravidian stone temples.",
        overview: "Chikkaballapura is famous for Nandi Hills (Nandidurga), offering cloud vistas and Bhoga Nandeeshwara Temple.",
        season: "September to March",
        timings: "6:00 AM - 6:00 PM",
        fee: "₹20 Entry Fee",
        attractions: ["Nandi Hills Viewpoint", "Bhoga Nandeeshwara Temple", "Skandagiri Night Trek"],
        reach: "Airport: Kempegowda Int'l Airport (35 km).",
        food: "Fresh Grape Juices, Crispy Masala Dosa, Filter Coffee.",
        map: "https://maps.google.com/?q=Nandi+Hills"
    },
    {
        id: "chikkamagaluru",
        name: "Chikkamagaluru",
        spot: "Mullayanagiri Peak & Coffee Estates",
        region: "Malnad",
        category: "Nature",
        image: "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The Coffee Land of Karnataka, offering mountain peaks, cascading waterfalls, and heritage homestays.",
        overview: "Chikkamagaluru is the birthplace of coffee in India and home to Mullayanagiri, the highest peak in Karnataka.",
        season: "September to March",
        timings: "Open 24 Hours",
        fee: "Free Entry",
        attractions: ["Mullayanagiri Peak", "Baba Budangiri", "Hebbe Falls", "Kudremukh National Park"],
        reach: "Airport: Mangaluru Airport (150 km). Road: Direct buses from Bengaluru.",
        food: "Malnad Thali, Akki Roti with Bamboo Shoot Curry, Filter Coffee.",
        map: "https://maps.google.com/?q=Mullayanagiri"
    },
    {
        id: "chitradurga",
        name: "Chitradurga",
        spot: "Chitradurga Stone Fort (Elusuttha Kote)",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "An impregnable stone fortress featuring seven concentric wall rings, secret passages, and rock legends.",
        overview: "Chitradurga is famous for 'Kallina Kote' (Stone Fort), a massive military stronghold with seven concentric rings of defensive stone walls and Obavana Kindi.",
        season: "October to March",
        timings: "6:00 AM - 6:00 PM",
        fee: "₹25 for Indians, ₹300 for Foreigners",
        attractions: ["Chitradurga Fort", "Obavana Kindi Crevice", "Hidimbeshwara Temple", "Chandravalli Caves"],
        reach: "Rail: Chitradurga Station. Highway: Located on NH-48.",
        food: "Davanagere-style Benne Dosa, Groundnut Chutney, Jolada Rotti.",
        map: "https://maps.google.com/?q=Chitradurga+Fort"
    },
    {
        id: "dakshina-kannada",
        name: "Dakshina Kannada (Mangaluru)",
        spot: "Panambur Beach & Kadri Manjunatha Temple",
        region: "Coastal",
        category: "Beach",
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
        shortDesc: "A coastal destination renowned for golden beaches, Tulunadu culture, seafood, and pilgrimage centers.",
        overview: "Headquartered in Mangaluru, Dakshina Kannada offers Panambur beach and temples like Dharmasthala and Kukke Subramanya.",
        season: "October to March",
        timings: "Open 24 Hours",
        fee: "Free Entry",
        attractions: ["Panambur Beach", "Kadri Temple", "Kukke Subramanya", "Dharmasthala Temple"],
        reach: "Airport: Mangaluru Int'l Airport. Rail: Mangaluru Central.",
        food: "Mangalorean Fish Curry, Kori Rotti, Neer Dosa.",
        map: "https://maps.google.com/?q=Panambur+Beach"
    },
    {
        id: "davanagere",
        name: "Davanagere",
        spot: "Harihareshwara Temple & Kunduvada Lake",
        region: "South Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1621252179027-94459d278660?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The butter dosa capital of Karnataka, combining Hoysala temple heritage with serene lakes.",
        overview: "Davanagere features the 12th-century Hoysala Harihareshwara Temple and is famous across India for Benne Dosa.",
        season: "October to March",
        timings: "6:00 AM - 8:00 PM",
        fee: "Free Entry",
        attractions: ["Harihareshwara Temple", "Kunduvada Kere Lake", "Bathi Gudda Viewpoint"],
        reach: "Rail: Davanagere Station. Highway: NH-48.",
        food: "Davanagere Benne Masala Dosa, Nargis Mandakki.",
        map: "https://maps.google.com/?q=Harihareshwara+Temple+Harihar"
    },
    {
        id: "dharwad",
        name: "Dharwad",
        spot: "Chandramouleshwara Temple & Unkal Lake",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The cultural hub of North Karnataka, famous for Badami Chalukyan stone temples and Dharwad Pedha.",
        overview: "Dharwad and Hubballi feature the 900-year-old Chandramouleshwara Temple and Unkal Lake.",
        season: "October to March",
        timings: "6:00 AM - 7:30 PM",
        fee: "Free Entry",
        attractions: ["Chandramouleshwara Temple", "Unkal Lake", "Nrupatunga Betta"],
        reach: "Airport: Hubballi Airport. Rail: Hubballi Junction.",
        food: "Dharwad Pedha, Jolada Rotti Meals, Girmit.",
        map: "https://maps.google.com/?q=Unkal+Lake+Hubli"
    },
    {
        id: "gadag",
        name: "Gadag",
        spot: "Trikuteshwara Temple & Lakkundi Stepwells",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1621252179027-94459d278660?auto=format&fit=crop&w=800&q=80",
        shortDesc: "An architectural landmark showcasing Kalyani Chalukya stone temples, ornate stepwells, and wind farms.",
        overview: "Gadag houses Trikuteshwara Temple and nearby Lakkundi, which features over 50 stone temples and stepwells.",
        season: "October to March",
        timings: "8:00 AM - 6:00 PM",
        fee: "Free Entry",
        attractions: ["Trikuteshwara Temple", "Lakkundi Stepwells", "Magadi Bird Sanctuary"],
        reach: "Rail: Gadag Junction. Highway: NH-67.",
        food: "Jowar Rotti, Badanekayi Yennegai, Girmit.",
        map: "https://maps.google.com/?q=Lakkundi+Gadag"
    },
    {
        id: "hassan",
        name: "Hassan",
        spot: "Belur, Halebeedu & Shravanabelagola",
        region: "South Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1621252179027-94459d278660?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The epicenter of Hoysala stone carving art and home to the world's tallest monolithic Jain statue.",
        overview: "Hassan contains UNESCO-recognized Hoysala temples at Belur and Halebeedu, and the 57-ft Gommateshwara monolith at Shravanabelagola.",
        season: "October to March",
        timings: "7:30 AM - 7:30 PM",
        fee: "Free Entry",
        attractions: ["Belur Chennakeshava Temple", "Halebeedu Hoysaleswara Temple", "Shravanabelagola Gommateshwara"],
        reach: "Rail: Hassan Junction. Highway: NH-75.",
        food: "Ragi Mudde with Soppu Saaru, Akki Roti.",
        map: "https://maps.google.com/?q=Belur+Temple"
    },
    {
        id: "haveri",
        name: "Haveri",
        spot: "Siddhesvara Temple & Bankapura Peacock Sanctuary",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1621252179027-94459d278660?auto=format&fit=crop&w=800&q=80",
        shortDesc: "Land of saints, Western Chalukya temples, world-famous red chillies, and peacock sanctuaries.",
        overview: "Haveri features the 11th-century Siddhesvara Chalukya temple and Bankapura Peacock Sanctuary.",
        season: "October to March",
        timings: "6:00 AM - 6:00 PM",
        fee: "Free Entry",
        attractions: ["Siddhesvara Temple", "Bankapura Peacock Sanctuary", "Kaginele Kanaka Guru Peetha"],
        reach: "Rail: Haveri Station. Highway: NH-48.",
        food: "Jolada Rotti, Byadgi Chilli Curries.",
        map: "https://maps.google.com/?q=Siddhesvara+Temple+Haveri"
    },
    {
        id: "kalaburagi",
        name: "Kalaburagi (Gulbarga)",
        spot: "Gulbarga Fort & Khwaja Bande Nawaz Dargah",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The historic Bahmani capital featuring medieval forts, vaulted mosques, and Sufi heritage.",
        overview: "Kalaburagi served as the capital of the Bahmani Sultanate and houses Gulbarga Fort and Khwaja Bande Nawaz Dargah.",
        season: "October to March",
        timings: "8:00 AM - 6:00 PM",
        fee: "Free Entry",
        attractions: ["Gulbarga Fort & Jama Masjid", "Khwaja Bande Nawaz Dargah", "Buddha Vihar"],
        reach: "Airport: Kalaburagi Airport. Rail: Kalaburagi Junction.",
        food: "Kalaburagi Tahari, Jolada Rotti, Malpuri Sweets.",
        map: "https://maps.google.com/?q=Gulbarga+Fort"
    },
    {
        id: "kodagu",
        name: "Kodagu (Coorg)",
        spot: "Abbey Falls, Raja's Seat & Dubare",
        region: "Malnad",
        category: "Nature",
        image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The Scotland of India, world-renowned for coffee estates, misty valleys, elephant camps, and Kodava culture.",
        overview: "Kodagu is a tranquil hill destination featuring coffee estates, Abbey Falls, Raja's Seat, and Dubare Elephant Camp.",
        season: "September to June",
        timings: "9:00 AM - 5:00 PM",
        fee: "₹15 - ₹50",
        attractions: ["Abbey Falls", "Raja's Seat Viewpoint", "Dubare Elephant Camp", "Bylakuppe Golden Temple"],
        reach: "Airport: Kannur Airport / Mangaluru Airport. Road: Mysuru Highway.",
        food: "Pandi Curry, Akki Oti, Kadambuttu.",
        map: "https://maps.google.com/?q=Madikeri+Coorg"
    },
    {
        id: "kolar",
        name: "Kolar",
        spot: "Kotilingeshwara Temple & Kolar Gold Fields (KGF)",
        region: "South Interior",
        category: "Pilgrimage",
        image: "https://images.unsplash.com/photo-1621252179027-94459d278660?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The Land of Gold, featuring a temple with 10 million Shiva Lingas and historic Chola-era architecture.",
        overview: "Kolar is historically famous for Kolar Gold Fields (KGF) and Kotilingeshwara Temple which hosts millions of Shiva Lingas.",
        season: "September to March",
        timings: "6:00 AM - 9:00 PM",
        fee: "Kotilingeshwara: ₹20",
        attractions: ["Kotilingeshwara Temple", "Kolaramma Temple", "KGF Gold Fields Ruins"],
        reach: "Airport: Kempegowda Int'l Airport (75 km). Highway: NH-75.",
        food: "Crispy Masala Dosa, Filter Coffee, Mysore Pak.",
        map: "https://maps.google.com/?q=Kotilingeshwara+Temple"
    },
    {
        id: "koppal",
        name: "Koppal",
        spot: "Anegundi & Mahadeva Temple Itagi",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The ancient Ramayana kingdom of Kishkindha at Anegundi and Western Chalukyan architectural gems.",
        overview: "Koppal lies across the river from Hampi. Anegundi is believed to be the Ramayana monkey kingdom Kishkindha.",
        season: "October to March",
        timings: "6:00 AM - 6:00 PM",
        fee: "Free Entry",
        attractions: ["Anegundi Village & Fort", "Anjanadri Hill (Hanuman Birthplace)", "Mahadeva Temple Itagi"],
        reach: "Rail: Koppal Station. Road: NH-67.",
        food: "Jolada Rotti, Sajje Rotti, Shenga Chutney.",
        map: "https://maps.google.com/?q=Anegundi+Karnataka"
    },
    {
        id: "mandya",
        name: "Mandya",
        spot: "Ranganathittu Bird Sanctuary & Srirangapatna",
        region: "South Interior",
        category: "Nature",
        image: "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The sugar city of Karnataka, featuring riverine bird sanctuaries, island fortresses, and royal dams.",
        overview: "Mandya houses Ranganathittu Bird Sanctuary, Tipu Sultan's island fortress Srirangapatna, and Brindavan Gardens.",
        season: "September to March",
        timings: "8:30 AM - 5:40 PM",
        fee: "Ranganathittu: ₹70",
        attractions: ["Ranganathittu Bird Sanctuary", "Srirangapatna Fort", "Brindavan Gardens KRS", "Shivanasamudra Falls"],
        reach: "Rail: Mandya Station. Highway: Bengaluru-Mysuru Expressway.",
        food: "Maddur Vada, Ragi Mudde with Naati Koli Curry.",
        map: "https://maps.google.com/?q=Ranganathittu+Bird+Sanctuary"
    },
    {
        id: "mysuru",
        name: "Mysuru (Mysore)",
        spot: "Mysore Palace & Chamundi Hill",
        region: "South Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1600100397608-f09070624022?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The Cultural Capital of Karnataka, world-renowned for Mysore Palace, royal Dasara processions, and silk.",
        overview: "Mysuru is famous for Mysore Palace, Chamundeshwari Temple atop Chamundi Hill, and royal heritage.",
        season: "October to March",
        timings: "10:00 AM - 5:30 PM",
        fee: "Palace: ₹100",
        attractions: ["Mysore Palace", "Chamundeshwari Temple", "Mysore Zoo", "St. Philomena's Cathedral"],
        reach: "Airport: Mysore Airport. Rail: Mysuru Junction.",
        food: "Mysore Pak, Mysore Masala Dosa, Filter Coffee.",
        map: "https://maps.google.com/?q=Mysore+Palace"
    },
    {
        id: "raichur",
        name: "Raichur",
        spot: "Raichur Fort & Deosugur Temple",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "A historic fortress region sandwiched between the Krishna and Tungabhadra rivers.",
        overview: "Raichur features stone fortifications built between the Krishna and Tungabhadra rivers.",
        season: "October to March",
        timings: "8:00 AM - 6:00 PM",
        fee: "Free Entry",
        attractions: ["Raichur Fort", "Deosugur Sugureshwara Temple", "Jaladurga Fort"],
        reach: "Rail: Raichur Junction.",
        food: "Jolada Rotti Meals, Shenga Pudi, Mirchi Bajji.",
        map: "https://maps.google.com/?q=Raichur+Fort"
    },
    {
        id: "ramanagara",
        name: "Ramanagara",
        spot: "Ramadevara Betta & Janapada Loka",
        region: "South Interior",
        category: "Nature",
        image: "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The Silk City, surrounded by granite monoliths, vulture conservation sanctuaries, and folk art museums.",
        overview: "Ramanagara is famous for silk markets, Ramadevara Betta Vulture Sanctuary, and as the filming site of 'Sholay'.",
        season: "September to March",
        timings: "9:00 AM - 4:30 PM",
        fee: "Ramadevara Betta: ₹25",
        attractions: ["Ramadevara Betta Vulture Sanctuary", "Janapada Loka Folk Museum", "Savandurga Monolith"],
        reach: "Airport: Bengaluru (75 km). Highway: Bengaluru-Mysuru Expressway.",
        food: "Maddur Vada, Thatte Idli, Ragi Mudde.",
        map: "https://maps.google.com/?q=Ramadevara+Betta"
    },
    {
        id: "shivamogga",
        name: "Shivamogga (Shimoga)",
        spot: "Jog Falls & Agumbe Rainforest",
        region: "Malnad",
        category: "Nature",
        image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The Gateway to the Malnad region, featuring India's famous Jog Falls and dense tropical rainforests.",
        overview: "Shivamogga features the 253m Jog Falls and Agumbe rainforest, known for high rainfall and sunsets.",
        season: "July to December",
        timings: "6:00 AM - 6:00 PM",
        fee: "Jog Falls: ₹15 Entry",
        attractions: ["Jog Waterfalls", "Agumbe Rainforest", "Sakrebyle Elephant Camp"],
        reach: "Airport: Shivamogga Airport. Rail: Shivamogga Town Station.",
        food: "Malanadu Thali, Midigayi Pickles, Jackfruit Chips.",
        map: "https://maps.google.com/?q=Jog+Falls"
    },
    {
        id: "tumakuru",
        name: "Tumakuru (Tumkur)",
        spot: "Devarayanadurga & Shivagange",
        region: "South Interior",
        category: "Pilgrimage",
        image: "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80",
        shortDesc: "An industrial and educational city surrounded by sacred hill ranges, natural springs, and temples.",
        overview: "Tumakuru is surrounded by Devarayanadurga hill station and Shivagange conical hill peak.",
        season: "October to March",
        timings: "6:00 AM - 7:00 PM",
        fee: "Free Entry",
        attractions: ["Devarayanadurga Hill Temples", "Shivagange Hill Peak", "Siddaganga Matha"],
        reach: "Airport: Kempegowda Int'l Airport. Highway: NH-48.",
        food: "Tumakuru Thatte Idli, Benne Dosa.",
        map: "https://maps.google.com/?q=Devarayanadurga"
    },
    {
        id: "udupi",
        name: "Udupi",
        spot: "St. Mary's Island, Malpe Beach & Krishna Matha",
        region: "Coastal",
        category: "Beach",
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
        shortDesc: "Coastal destination famous for basalt rock islands, Malpe sea walk, and Sri Krishna Temple.",
        overview: "Udupi is famous for Sri Krishna Matha, Malpe Beach, and St. Mary's Island hexagonal basalt rock formations.",
        season: "October to March",
        timings: "5:00 AM - 9:00 PM",
        fee: "Ferry: ₹400",
        attractions: ["St. Mary's Island", "Malpe Sea Walk", "Sri Krishna Matha", "Kapu Lighthouse"],
        reach: "Airport: Mangaluru Airport (60 km). Rail: Udupi Station.",
        food: "Udupi Masala Dosa, Neer Dosa, Gadbad Ice Cream.",
        map: "https://maps.google.com/?q=St+Marys+Island+Udupi"
    },
    {
        id: "uttara-kannada",
        name: "Uttara Kannada (Karwar)",
        spot: "Gokarna Om Beach, Murudeshwar & Dandeli",
        region: "Coastal",
        category: "Beach",
        image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
        shortDesc: "A district offering Gokarna beach treks, Murudeshwar's Shiva statue, and river rafting in Dandeli.",
        overview: "Uttara Kannada offers Om Beach in Gokarna, 123-ft Shiva statue in Murudeshwar, and rafting in Dandeli.",
        season: "October to March",
        timings: "Open 24 Hours",
        fee: "Free Entry",
        attractions: ["Gokarna Om Beach", "Murudeshwar Shiva Statue", "Dandeli River Rafting", "Yana Caves"],
        reach: "Airport: Goa Dabolim. Rail: Gokarna Road / Murdeshwar.",
        food: "Karwar Fish Curry, Banana Pancakes.",
        map: "https://maps.google.com/?q=Om+Beach+Gokarna"
    },
    {
        id: "vijayanagara",
        name: "Vijayanagara",
        spot: "Hampi UNESCO World Heritage Site",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The capital of the Vijayanagara Empire, featuring stone chariots, royal baths, and boulder landscapes.",
        overview: "Vijayanagara houses Hampi, a UNESCO World Heritage site with over 1,600 monuments including the Stone Chariot.",
        season: "November to February",
        timings: "8:30 AM - 5:30 PM",
        fee: "₹40 for Indians, ₹600 for Foreigners",
        attractions: ["Vittala Temple Stone Chariot", "Virupaksha Temple", "Lotus Mahal", "Elephant Stables"],
        reach: "Rail: Hospet Junction (13 km). Airport: Jindal Vijaynagar.",
        food: "South Indian Thali, Fresh Coconut Water.",
        map: "https://maps.google.com/?q=Hampi+Karnataka"
    },
    {
        id: "vijayapura",
        name: "Vijayapura (Bijapur)",
        spot: "Gol Gumbaz & Ibrahim Rauza",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The Deccan Sultanate capital famous for the world's second-largest dome and its acoustic Whispering Gallery.",
        overview: "Vijayapura features Gol Gumbaz with its unsupported 44m dome and Whispering Gallery.",
        season: "October to March",
        timings: "6:00 AM - 6:00 PM",
        fee: "₹25 for Indians, ₹300 for Foreigners",
        attractions: ["Gol Gumbaz", "Ibrahim Rauza", "Jama Masjid", "Bara Kaman"],
        reach: "Airport: Kalaburagi Airport. Rail: Vijayapura Station.",
        food: "Jolada Rotti Oota, Shenga Chutney, Badanekayi Yennegai.",
        map: "https://maps.google.com/?q=Gol+Gumbaz+Bijapur"
    },
    {
        id: "yadgir",
        name: "Yadgir",
        spot: "Yadgir Fort & Sleeping Buddha Hill",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "A hill fort region featuring a monolithic boulder citadel and hill ranges shaped like a resting Buddha.",
        overview: "Yadgir features a single-boulder hill fort and the Shahapur hill range shaped like a Sleeping Buddha.",
        season: "October to March",
        timings: "8:00 AM - 5:00 PM",
        fee: "Free Entry",
        attractions: ["Yadgir Hill Fort", "Sleeping Buddha Hill Shahapur", "Shorapur Fort"],
        reach: "Rail: Yadgir Station. Road: State Highways.",
        food: "Jolada Rotti, Shenga Pudi, Badanekayi Curry.",
        map: "https://maps.google.com/?q=Yadgir+Fort"
    }
];
