const districts = [
    {
        id: "bagalkote",
        name: "Bagalkote",
        spot: "Badami Cave Temples & Pattadakal",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The cradle of Indian temple architecture featuring ancient sandstone rock-cut caves and UNESCO World Heritage monuments.",
        overview: "Bagalkote district served as the capital of the Early Chalukya dynasty (540–757 CE). The region is world-renowned for Badami's four monolithic rock-cut cave temples carved directly into red sandstone cliffs overlooking the Agastya Lake. Nearby, Pattadakal houses a UNESCO World Heritage site showcasing a fusion of Nagara (North Indian) and Dravidian (South Indian) architectural styles. Aihole, often termed the 'Cradle of Indian Architecture,' features over 120 stone temples built between the 6th and 8th centuries.",
        season: "October to March (Mild winter weather)",
        timings: "9:00 AM - 5:30 PM (All days)",
        fee: "₹25 for Indians, ₹300 for Foreigners (Covers main cave complex)",
        attractions: [
            "Badami Sandstone Cave Temples (Lord Shiva, Vishnu, and Jain Tirthankaras)",
            "Pattadakal UNESCO Group of Monuments (Virupaksha & Mallikarjuna Temples)",
            "Aihole Archaeological Complex & Durga Temple",
            "Agastya Tirtha Lake & Bhutanatha Group of Temples",
            "Banashankari Amma Temple at Cholachagudd"
        ],
        reach: "Nearest Airport: Hubballi Airport (HBX, ~105 km). Rail: Badami Railway Station (BDM) is directly connected to Hubballi, Bengaluru, and Solapur. Road: Well-connected via State Highway 57.",
        food: "Authentic North Karnataka Oota featuring Jolada Rotti (Sorghum flatbread), Shenga Chutney (Spiced Peanut Powder), Badanekayi Yennegai (Stuffed Brinjal), and Badami Pedha.",
        map: "https://maps.google.com/?q=Badami+Cave+Temples"
    },
    {
        id: "ballari",
        name: "Ballari (Bellary)",
        spot: "Ballari Fort Monolith & Sandur Valley",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80",
        shortDesc: "A historic fortress city anchored by a massive granite monolith hill fort and the lush, mineral-rich Sandur valley.",
        overview: "Ballari district is distinguished by the majestic Ballari Fort, constructed atop the 'Ballari Gudda'—a sprawling single-rock monolith that is the world's second-largest monolithic hill. Built initially by Hanumappa Nayaka during the Vijayanagara era and later fortified by Hyder Ali and British engineers, the fort is divided into the Upper Fort and Lower Fort. Beyond its rock fortifications, the nearby Sandur valley offers dense forests, rich iron ore reserves, and centuries-old Badami Chalukyan and Rashtrakuta temples.",
        season: "October to February",
        timings: "8:00 AM - 6:00 PM",
        fee: "Free entry",
        attractions: [
            "Ballari Fort Monolithic Citadel (Upper & Lower Forts)",
            "Sandur Kumaraswamy Temple Complex (8th-10th Century)",
            "Mincheri Hill Viewpoint",
            "Kuntegadda Park & Bellary Zoo",
            "Narihalla Reservoir Dam in Sandur"
        ],
        reach: "Nearest Airport: Jindal Vijaynagar Airport (VDY, ~40 km). Rail: Ballari Junction (BAY) is a major rail hub connecting Bengaluru, Hyderabad, and Goa.",
        food: "Jowar Rotti Meals, Uggani (Seasoned Puffed Rice) paired with Spicy Mirchi Bajji, and Gongaura Pickle.",
        map: "https://maps.google.com/?q=Ballari+Fort"
    },
    {
        id: "belagavi",
        name: "Belagavi (Belgaum)",
        spot: "Gokak Falls & Belagavi Fort",
        region: "North Interior",
        category: "Nature",
        image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The second capital of Karnataka, featuring horseshoe waterfalls, historic forts, and Western Ghat foothills.",
        overview: "Belagavi lies along the Western Ghats near the borders of Maharashtra and Goa. The district is celebrated for Gokak Falls, where the Ghataprabha River plunges 52 meters down a sandstone cliff into a horseshoe-shaped gorge, spanning a historic 201-meter suspension bridge. In Belagavi city, the 13th-century Belagavi Fort houses the ancient Kamal Basti (Jain Temple) featuring a 72-petaled lotus carved into stone. The district is also steeped in freedom struggle lore, being the home of Queen Chennamma of Kittur.",
        season: "July to January (Monsoon for waterfalls, winter for sightseeing)",
        timings: "Fort: 8:00 AM - 6:30 PM | Gokak Falls: 8:00 AM - 6:00 PM",
        fee: "Free (Nominal vehicle parking charges)",
        attractions: [
            "Gokak Falls & Historic Cable Suspension Bridge",
            "Belagavi Fort & Kamal Basti Jain Temple",
            "Kittur Fort & Rani Chennamma Memorial Museum",
            "Rajhansgad Yellur Fort (Hilltop panoramic view)",
            "Military Mahadeva Temple & Rakaskop Dam"
        ],
        reach: "Airport: Belagavi Airport (IXG). Rail: Belagavi Railway Station (BGM) on the South Western Railway line.",
        food: "Belagavi Kunda (Milk Sweet), Mandige (Layered Flatbread), Sol Kadi, and Butter Dosa.",
        map: "https://maps.google.com/?q=Gokak+Falls"
    },
    {
        id: "bengaluru-rural",
        name: "Bengaluru Rural",
        spot: "Ghati Subramanya & Devanahalli Fort",
        region: "South Interior",
        category: "Pilgrimage",
        image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80",
        shortDesc: "A serene getaway surrounding the state capital, offering trekking peaks, silk production hubs, and ancient shrines.",
        overview: "Encircling the capital city, Bengaluru Rural blends rural landscapes with rich historic heritage. It houses Devanahalli Fort, built in 1501 by Malla Byre Gowda and famous as the birthplace of Tipu Sultan. The district is a major spiritual destination due to Ghati Subramanya, an ancient temple where Lord Subramanya and Lord Lakshmi Narasimha are sculpted back-to-back on a single stone. Adventurers visit Makalidurga and Shivagange for granite rock climbing and wilderness treks.",
        season: "September to March",
        timings: "Ghati Subramanya Temple: 6:00 AM - 8:30 PM",
        fee: "Free Entry",
        attractions: [
            "Ghati Subramanya Temple",
            "Devanahalli Fort & Tipu Sultan Birthplace Memorial",
            "Makalidurga Fort Trekking Hill & Railway Track Loop",
            "Vijayapura Silk Weaving Hubs",
            "Doddaballapura Industrial & Heritage Corridors"
        ],
        reach: "Airport: Kempegowda International Airport (BLR) lies directly within this district. Rail: Connected via Doddaballapura and Devanahalli stations.",
        food: "Ragi Mudde (Finger Millet Balls) with Avarekalu Saaru, Akki Roti, and Fresh Coconut Water.",
        map: "https://maps.google.com/?q=Ghati+Subramanya+Temple"
    },
    {
        id: "bengaluru-urban",
        name: "Bengaluru Urban",
        spot: "Bengaluru Palace, Lalbagh & Cubbon Park",
        region: "South Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The Silicon Valley of Asia, seamlessly blending 19th-century royal palaces with urban greenery and tech hubs.",
        overview: "Bengaluru Urban is the capital city of Karnataka. Founded by Kempe Gowda I in 1537, it has evolved into India's primary technology hub while preserving its legacy as the 'Garden City.' Major highlights include the Tudor-style Bengaluru Palace, modeled after England's Windsor Castle; Lalbagh Botanical Garden, home to a 130-year-old Glass House inspired by London's Crystal Palace; and Vidhana Soudha, the seat of Karnataka's state legislature constructed in Neo-Dravidian granite architecture.",
        season: "Year-Round (Best from October to February)",
        timings: "Bengaluru Palace: 10:00 AM - 5:30 PM | Lalbagh: 6:00 AM - 7:00 PM",
        fee: "Palace: ₹240 for Indians | Lalbagh: ₹25 Entry",
        attractions: [
            "Bengaluru Palace (Tudor Architecture & Royal Collections)",
            "Lalbagh Botanical Garden & Glasshouse Flower Shows",
            "Vidhana Soudha & High Court of Karnataka (Attara Kacheri)",
            "Cubbon Park & Visvesvaraya Industrial and Technological Museum",
            "ISKCON Sri Radha Krishna Temple Rajajinagar",
            "Bannerghatta Biological Park (Safari & Butterfly Park)"
        ],
        reach: "Airport: Kempegowda International Airport (BLR, ~35 km from city center). Rail: KSR Bengaluru (SBC) & Yesvantpur (YPR). Metro: Namma Metro Green & Purple lines.",
        food: "Crispy Benne Masala Dosa, Filter Coffee, Mysore Pak, Rava Idli, and Street Food at V.V. Puram Food Street.",
        map: "https://maps.google.com/?q=Bangalore+Palace"
    },
    {
        id: "bidar",
        name: "Bidar",
        spot: "Bidar Fort & Bahmani Sultanate Tombs",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "Karnataka's northern crown, packed with medieval Islamic architecture, Bahmani forts, and Bidriware metal craft.",
        overview: "Situated on a red laterite plateau at the northernmost tip of Karnataka, Bidar served as the capital of the Bahmani Kingdom and Barid Shahi Sultanate between the 14th and 16th centuries. The massive Bidar Fort complex features 30+ structures including Rangeen Mahal (adorned with mother-of-pearl tilework), Tarkash Mahal, and Solah Khamba Mosque. Bidar is also world-famous for Bidriware—a unique handicraft where zinc-copper alloy is inlaid with silver wires and blackened using earth from the fort.",
        season: "October to March",
        timings: "9:00 AM - 5:00 PM",
        fee: "Free Entry",
        attractions: [
            "Bidar Fort Complex & Rangeen Mahal Palace",
            "Mahmud Gawan Islamic Madrasa (15th Century University)",
            "Ashtur Bahmani Sultanate Tombs",
            "Gurudwara Nanak Jhira Sahib (Sacred Sikh pilgrimage site with natural spring)",
            "Papnash Shiva Temple in a picturesque valley"
        ],
        reach: "Airport: Bidar Airport (IATA: IXX) / Kalaburagi Airport (110 km). Rail: Connected via Bidar Railway Station.",
        food: "Naan Qalia, Bidri Mutton Biryani, Tahari, and Sweet Jalabi.",
        map: "https://maps.google.com/?q=Bidar+Fort"
    },
    {
        id: "chamarajanagar",
        name: "Chamarajanagar",
        spot: "Bandipur National Park & BR Hills",
        region: "South Interior",
        category: "Wildlife",
        image: "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=800&q=80",
        shortDesc: "A wilderness haven featuring tiger reserves, dense elephant corridors, and sacred mountain ranges.",
        overview: "Forming the southern tip of Karnataka bordering Tamil Nadu and Kerala, Chamarajanagar is one of the state's most ecologically rich districts. It shelters Bandipur National Park—a cornerstone of Project Tiger—and the Biligirirangana Hills (BR Hills) Wildlife Sanctuary, where the Western and Eastern Ghats converge. The district is also spiritual, home to Male Mahadeshwara Betta, a sacred hill shrine visited by millions of pilgrims annually.",
        season: "October to May (Best for wildlife sightings)",
        timings: "Bandipur Safari: Morning (6:00 AM - 9:00 AM) & Evening (3:00 PM - 6:00 PM)",
        fee: "Bus Safari: ~₹350 | Jeep Safari: ~₹1,500 per head",
        attractions: [
            "Bandipur Tiger Reserve & National Park Safari",
            "Biligiriranga Hills (BR Hills) Temple & Sanctuary",
            "Male Mahadeshwara Betta (MM Hills) Shrine",
            "Gaganachukki & Bharachukki Waterfalls (Shivanasamudra)",
            "Suvarnavathi Dam & Reservoir"
        ],
        reach: "Nearest Airport: Mysore Airport (MYQ, ~70 km). Highway access via Mysuru-Ooty National Highway (NH-766).",
        food: "Traditional South Karnataka Banana Leaf Thali, Naati Koli Saaru, and Wild Forest Honey.",
        map: "https://maps.google.com/?q=Bandipur+National+Park"
    },
    {
        id: "chikkaballapura",
        name: "Chikkaballapura",
        spot: "Nandi Hills & Bhoga Nandeeshwara Temple",
        region: "South Interior",
        category: "Nature",
        image: "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80",
        shortDesc: "Famous hill station for cloud-sea sunrises, adventure night treks, and ancient Dravidian stone temples.",
        overview: "Chikkaballapura is famous for Nandi Hills (Nandidurga), an ancient hill fortress situated 1,478 meters above sea level. Popular for early-morning sea-of-clouds vistas, Nandi Hills was used as a summer retreat by Tipu Sultan and features the cliffside 'Tipu Drop.' At the base of the hill in Nandi village stands Bhoga Nandeeshwara Temple—one of Karnataka's oldest temples, featuring ornate 9th-century Dravidian stone architecture built across the Bana, Chola, Hoysala, and Vijayanagara eras.",
        season: "September to March (Early mornings year-round for fog views)",
        timings: "Nandi Hills: 6:00 AM - 6:00 PM",
        fee: "₹20 Entry Fee + Vehicle Parking",
        attractions: [
            "Nandi Hills Sunrise Point & Tipu Drop Cliff",
            "Bhoga Nandeeshwara Temple Complex at Nandi Village",
            "Skandagiri (Kalavara Durga) Night Trek Peak",
            "Muddenahalli (Birthplace & Museum of Sir M. Visvesvaraya)",
            "Kailasagiri Cave Temples near Chintamani"
        ],
        reach: "Nearest Airport: Kempegowda International Airport (BLR) is just 35 km away. Connected via NH-44 highway.",
        food: "Chikkaballapura Fresh Grape Juices, Crispy Masala Dosa, and Filter Coffee.",
        map: "https://maps.google.com/?q=Nandi+Hills"
    },
    {
        id: "chikkamagaluru",
        name: "Chikkamagaluru",
        spot: "Mullayanagiri Peak & Coffee Estates",
        region: "Malnad",
        category: "Nature",
        image: "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The Coffee Land of Karnataka, offering mountain peaks, cascading waterfalls, and heritage homestays.",
        overview: "Chikkamagaluru is celebrated as the birthplace of coffee in India, after the Sufi saint Baba Budan brought seven raw coffee beans from Yemen in 1670 and planted them in these hills. The district features Mullayanagiri, the highest peak in Karnataka (1,930 meters), offering trekking trails and panoramic valley views. Surrounded by the Western Ghats, the region is filled with sprawling coffee plantations, dense shola forests, and pristine waterfalls.",
        season: "September to March (Monsoons from June to August for waterfall chasing)",
        timings: "Trekking & Trails open throughout the day",
        fee: "Free Entry (Forest checkpost fees apply for specific vehicle trails)",
        attractions: [
            "Mullayanagiri Peak (Highest point in Karnataka)",
            "Baba Budangiri (Datta Peetha) Hill Range",
            "Hebbe Falls & Jhari (Dhabdhabe) Waterfalls",
            "Kudremukh National Park & Peak Trek",
            "Bhadra Wildlife Sanctuary (Lakkavalli Tiger Reserve Jeep Safari)",
            "Belavadi Veera Narayana Hoysala Temple"
        ],
        reach: "Nearest Airport: Mangaluru International Airport (IXE, ~150 km). Road: Direct bus services from Bengaluru (240 km).",
        food: "Authentic Malnad Thali, Akki Roti with Bamboo Shoot Curry (Kani), Halasina Kayi (Jackfruit) Curry, and Fresh Filter Coffee.",
        map: "https://maps.google.com/?q=Mullayanagiri"
    },
    {
        id: "chitradurga",
        name: "Chitradurga",
        spot: "Chitradurga Stone Fort (Elusuttha Kote)",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "An impregnable stone fortress featuring seven concentric wall rings, secret passages, and rock legends.",
        overview: "Chitradurga is famous for 'Kallina Kote' (Stone Fort), a massive military stronghold built across the 10th and 18th centuries by the Rashtrakutas, Chalukyas, Hoysalas, and Nayakas of Chitradurga. The fort is built with seven concentric rings of defensive stone walls ('Elusuttha Kote'), 38 secret entrances, 35 palace complexes, and 18 ancient temples. It is also famous for 'Obavana Kindi'—a narrow rock crevice where heroine Onake Obavva single-handedly fought off attacking forces of Hyder Ali.",
        season: "October to March",
        timings: "6:00 AM - 6:00 PM",
        fee: "₹25 for Indians, ₹300 for Foreigners",
        attractions: [
            "Chitradurga Fort & Obavana Kindi Crevice",
            "Ekanatheshwari & Hidimbeshwara Temples inside Fort",
            "Chandravalli Caves & Lake (Ancient monastic rock shelters)",
            "Vani Vilasa Sagara Dam (Mari Kanive Dam built in 1907)",
            "Jogimatti Hill Station & Forest Reserve"
        ],
        reach: "Rail: Chitradurga Railway Station (CTA). Highway: Situated directly on the Bengaluru-Mumbai National Highway (NH-48).",
        food: "Davanagere-style Benne Dosa, Groundnut Chutney, Jolada Rotti Oota, and Spicy Menasinakayi Bajji.",
        map: "https://maps.google.com/?q=Chitradurga+Fort"
    },
    {
        id: "dakshina-kannada",
        name: "Dakshina Kannada (Mangaluru)",
        spot: "Panambur Beach & Kadri Manjunatha Temple",
        region: "Coastal",
        category: "Beach",
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
        shortDesc: "A coastal destination renowned for golden beaches, Tulunadu culture, seafood, and pilgrimage centers.",
        overview: "Dakshina Kannada, headquartered in the coastal port city of Mangaluru, is the heart of Tulunadu culture. Flanked by the Arabian Sea on the west and the Western Ghats on the east, it offers a coastline with Panambur, Tannirbhavi, and Someshwara beaches. The district is also a major pilgrimage corridor, housing Mangaladevi Temple (from which Mangaluru gets its name), Kadri Manjunatha Temple (featuring a 1,000-year-old bronze statue), Dharmasthala, and Kukke Subramanya.",
        season: "October to March",
        timings: "Beaches: Open 24 Hours | Temples: 6:00 AM - 8:30 PM",
        fee: "Free Entry across beaches",
        attractions: [
            "Panambur Beach (Jet skis & International Kite Festival)",
            "Tannirbhavi Beach & Tree Park",
            "Kadri Manjunatha Temple & Mangaladevi Temple",
            "Kukke Subramanya Temple (Snake deity pilgrimage shrine)",
            "Dharmasthala Manjunatha Temple & Bahubali Monolith",
            "Pilikula Nisargadhama (Biological Park, Heritage Village & Planetarium)"
        ],
        reach: "Airport: Mangaluru International Airport (IXE). Rail: Mangaluru Central (MAQ) and Mangaluru Junction (MAJN). Port: New Mangalore Port.",
        food: "Mangalorean Fish Curry, Kori Rotti (Chicken Curry with Rice Wafers), Neer Dosa, Anjal (Seer Fish) Fry, and Pabbad's Ice Cream Sundaes.",
        map: "https://maps.google.com/?q=Panambur+Beach"
    },
    {
        id: "davanagere",
        name: "Davanagere",
        spot: "Harihareshwara Temple & Kunduvada Lake",
        region: "South Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1621252179027-94459d278660?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The butter dosa capital of Karnataka, combining Hoysala temple heritage with serene lakes.",
        overview: "Located in central Karnataka along the banks of the Tungabhadra River, Davanagere transitioned from a historical textile city into a major culinary and educational hub. In the nearby town of Harihar stands the Harihareshwara Temple, a 12th-century Hoysala architectural marvel dedicated to a union deity combining Lord Shiva and Lord Vishnu. The city is equally famous across South India for its signature Butter Dosa (Davanagere Benne Dosa).",
        season: "October to March",
        timings: "Harihareshwara Temple: 6:00 AM - 8:00 PM",
        fee: "Free Entry",
        attractions: [
            "Harihareshwara Temple at Harihar (1223 CE Hoysala Temple)",
            "Kunduvada Kere Lake & Promenade Walkway",
            "Bathi Gudda Hill Viewpoint & Bathi Lake",
            "Santi Bennur Pushkarani (Historic Royal Bathing Tank)",
            "Glass House Park Davanagere"
        ],
        reach: "Rail: Davanagere Railway Station (DVG) on the main Bengaluru-Hubballi rail line. Road: Located on NH-48.",
        food: "Davanagere Benne Masala Dosa, Open Butter Dosa, Nargis Mandakki (Spiced Puffed Rice), and Menasinakayi Bajji.",
        map: "https://maps.google.com/?q=Harihareshwara+Temple+Harihar"
    },
    {
        id: "dharwad",
        name: "Dharwad",
        spot: "Chandramouleshwara Temple & Unkal Lake",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The cultural hub of North Karnataka, famous for Badami Chalukyan stone temples, classical music, and Dharwad Pedha.",
        overview: "Dharwad (forming a twin-city urban agglomeration with Hubballi) is the cultural and literary capital of North Karnataka. It is famous for its Hindustani classical music traditions, having produced legends like Pandit Bhimsen Joshi and Gangubai Hangal. Architectural marvels include the 900-year-old Chandramouleshwara Temple in Hubballi—a Badami Chalukya-era black granite temple with four carved portals and 12 engraved stone pillars.",
        season: "October to March",
        timings: "Chandramouleshwara Temple: 6:00 AM - 7:30 PM | Unkal Lake: 8:00 AM - 8:00 PM",
        fee: "Free Entry",
        attractions: [
            "Chandramouleshwara Temple (Badami Chalukya Architecture)",
            "Unkal Lake & Swami Vivekananda Statue Island",
            "Nrupatunga Betta Hill Viewpoint",
            "Shri Siddharoodha Swamy Matha Hubballi",
            "Indira Gandhi Glass House Park"
        ],
        reach: "Airport: Hubballi Airport (HBX). Rail: Shree Siddharoodha Swamy Hubballi Junction (UBL)—home to the world's longest railway platform.",
        food: "Dharwad Pedha (GI Tagged milk sweet), Jolada Rotti Meals with Girmit (Spiced puffed rice snack).",
        map: "https://maps.google.com/?q=Unkal+Lake+Hubli"
    },
    {
        id: "gadag",
        name: "Gadag",
        spot: "Trikuteshwara Temple & Lakkundi Stepwells",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1621252179027-94459d278660?auto=format&fit=crop&w=800&q=80",
        shortDesc: "An architectural landmark showcasing Kalyani Chalukya stone temples, ornate stepwells, and wind farms.",
        overview: "Gadag district is an architectural jewel box of Western Chalukya (Kalyani Chalukya) stone sculpture. The Trikuteshwara Temple in Gadag city features triple-shrine architecture dedicated to Shiva, Brahma, and Surya, alongside a Saraswati temple noted for stone carvings. Just 11 km away lies Lakkundi, an ancient archaeological site featuring over 50 stone temples, 29 stepwells (Kalyanis), and centuries-old inscriptions. Gadag is also a renewable energy leader with sprawling wind farm hills.",
        season: "October to March",
        timings: "8:00 AM - 6:00 PM",
        fee: "Free Entry",
        attractions: [
            "Trikuteshwara & Saraswati Temple Complex",
            "Lakkundi Heritage Village & Stepwells (Musukina Bavi & Lakkundi Museum)",
            "Veeranarayana Temple Gadag (Associated with poet Kumaravyasa)",
            "Magadi Bird Sanctuary (Winter refuge for Bar-headed Geese)",
            "Kappathagudda Medicinal Forest Hills"
        ],
        reach: "Rail: Gadag Junction (GDG) connects directly to Hubballi, Bengaluru, and Solapur. Road: Connected via NH-67.",
        food: "Jowar Rotti, Badanekayi Yennegai, Shenga Pudi, and Puffed Rice Girmit.",
        map: "https://maps.google.com/?q=Lakkundi+Gadag"
    },
    {
        id: "hassan",
        name: "Hassan",
        spot: "Belur, Halebeedu & Shravanabelagola",
        region: "South Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1621252179027-94459d278660?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The epicenter of Hoysala stone carving art and home to the world's tallest monolithic Jain statue.",
        overview: "Hassan district is the heartland of the Hoysala Empire (10th–14th centuries). Belur's Chennakeshava Temple and Halebeedu's Hoysaleswara Temple showcase soapstone friezes depicting Hindu epics, animals, and dancers (Madanikas). Nearby Shravanabelagola features the 57-foot-tall monolithic statue of Lord Gommateshwara Bahubali, carved out of a single granite hill peak in 981 CE, which hosts the Mahamastakabhisheka festival every 12 years.",
        season: "October to March",
        timings: "Temples: 7:30 AM - 7:30 PM | Shravanabelagola: 6:30 AM - 6:00 PM",
        fee: "Free Entry (Option to hire certified ASI guides)",
        attractions: [
            "Chennakeshava Temple at Belur",
            "Hoysaleswara & Kedareshwara Temples at Halebeedu",
            "Shravanabelagola Gommateshwara Monolith Hill (Vindhyagiri)",
            "Shettihalli Rosary Church Ruins (Submerged floating church)",
            "Gorur Dam across Hemavathi River"
        ],
        reach: "Nearest Airport: Bengaluru (180 km) / Mysuru (115 km). Rail: Hassan Junction (HAS). Road: Located on NH-75 expressway.",
        food: "Ragi Mudde with Soppu Saaru, Akki Roti with Coconut Chutney, and South Indian Filter Coffee.",
        map: "https://maps.google.com/?q=Belur+Temple"
    },
    {
        id: "haveri",
        name: "Haveri",
        spot: "Siddhesvara Temple & Bankapura Peacock Sanctuary",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1621252179027-94459d278660?auto=format&fit=crop&w=800&q=80",
        shortDesc: "Land of saints, Western Chalukya temples, world-famous red chillies, and peacock sanctuaries.",
        overview: "Haveri is rich in folklore, literature, and architectural history. It is the birthplace of celebrated Kannada saint-poets Kanaka Dasa and Sarvajna. The district features the 11th-century Siddhesvara Temple in Haveri town, a prime example of Western Chalukyan staggered-square architecture. In Bankapura, ruins of a 16th-century fort house one of India's few dedicated Peacock Sanctuaries, where thousands of wild peacocks roam among historical ruins.",
        season: "October to March",
        timings: "Siddhesvara Temple: 6:00 AM - 6:00 PM | Bankapura Sanctuary: 9:00 AM - 5:00 PM",
        fee: "Free Entry across main monuments",
        attractions: [
            "Siddhesvara Temple Haveri (11th Century Chalukyan Architecture)",
            "Bankapura Peacock Sanctuary & Fort Ruins",
            "Kaginele Kanaka Guru Peetha (Memorial & Park dedicated to Kanaka Dasa)",
            "Galageshwara Temple at Galaganatha (Tungabhadra riverfront)",
            "Byadgi Spice Market (World famous for Byadgi Red Chillies)"
        ],
        reach: "Rail: Haveri Railway Station (HVR) on the Bengaluru-Hubballi main line. Road: Situated along NH-48.",
        food: "Jolada Rotti Meals, Byadgi Chilli Spiced Curries, Puffed Rice Snacks, and Pedha.",
        map: "https://maps.google.com/?q=Siddhesvara+Temple+Haveri"
    },
    {
        id: "kalaburagi",
        name: "Kalaburagi (Gulbarga)",
        spot: "Gulbarga Fort & Khwaja Bande Nawaz Dargah",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The historic Bahmani capital featuring medieval forts, vaulted mosques, and Sufi heritage.",
        overview: "Kalaburagi served as the initial capital of the Bahmani Sultanate from 1347 to 1425 CE. The district contains Gulbarga Fort, rebuilt by Kabaja Jahan in 1347, which houses the Jama Masjid—a mosque constructed in 1367 modeled after the Great Mosque of Cordoba in Spain, featuring vaulted domes and no open courtyard. Kalaburagi is also a Sufi spiritual hub due to the Khwaja Bande Nawaz Dargah, a monument exhibiting Indo-Saracenic architectural influences.",
        season: "October to March",
        timings: "Fort: 8:00 AM - 6:00 PM | Dargah: 5:00 AM - 10:00 PM",
        fee: "Free Entry",
        attractions: [
            "Gulbarga Fort & Jama Masjid (Spanish-style vaulted mosque)",
            "Hazrat Khwaja Bande Nawaz Dargah Shrine",
            "Sharana Basaveshwara Temple (18th Century Lingayat Shrine)",
            "Buddha Vihar (Sprawling Buddhist pilgrimage center)",
            "Sannati Archaeological Site (Ashokan Rock Edicts on the Bhima River)"
        ],
        reach: "Airport: Kalaburagi Airport (GBR). Rail: Kalaburagi Junction (KLBG) on the Mumbai-Chennai main railway trunk line.",
        food: "Kalaburagi Tahari (Spiced Mutton Rice), Jolada Rotti Oota with Shenga Chutney, and Malpuri Sweets.",
        map: "https://maps.google.com/?q=Gulbarga+Fort"
    },
    {
        id: "kodagu",
        name: "Kodagu (Coorg)",
        spot: "Abbey Falls, Raja's Seat & Dubare",
        region: "Malnad",
        category: "Nature",
        image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The Scotland of India, world-renowned for coffee estates, misty valleys, elephant camps, and Kodava culture.",
        overview: "Kodagu is a hill station situated on the slopes of the Western Ghats. Known for its climate, rolling hills, coffee plantations, and spice gardens (cardamom and pepper), it is also home to the Kodava martial community with their unique cultural traditions. Highlights include Raja's Seat, a garden viewpoint used by the Kings of Kodagu to watch sunsets; Abbey Falls, tucked inside private coffee estates; Talakaveri, the river origin of the Kaveri; and Dubare Elephant Camp along the Kaveri riverfront.",
        season: "September to June",
        timings: "Abbey Falls: 9:00 AM - 5:00 PM | Raja's Seat: 5:30 AM - 8:00 PM",
        fee: "Nominal fees ranging between ₹15 and ₹50",
        attractions: [
            "Abbey Falls & Iruppu Falls",
            "Raja's Seat Sunset Viewpoint & Musical Fountains",
            "Dubare Elephant Camp & River Rafting",
            "Talakaveri (Source of Kaveri River) & Brahmagiri Peak",
            "Namdroling Monastery (Golden Temple Bylakuppe Tibetan Settlement)",
            "Madikeri Fort & Omkareshwara Temple"
        ],
        reach: "Nearest Airport: Kannur International Airport (CNN, ~90 km) / Mangaluru Airport (140 km). Highway road access via Mysuru.",
        food: "Pandi Curry (Pork Curry cooked with Kachampuli vinegar), Akki Oti (Rice Flatbread), Kadambuttu (Steamed Rice Balls), and Bamboo Shoot Curry.",
        map: "https://maps.google.com/?q=Madikeri+Coorg"
    },
    {
        id: "kolar",
        name: "Kolar",
        spot: "Kotilingeshwara Temple & Kolar Gold Fields (KGF)",
        region: "South Interior",
        category: "Pilgrimage",
        image: "https://images.unsplash.com/photo-1621252179027-94459d278660?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The Land of Gold, featuring a temple with 10 million Shiva Lingas and historic Chola-era architecture.",
        overview: "Kolar district is historically famous as the 'Land of Gold' due to the Kolar Gold Fields (KGF), one of the deepest gold mines in the world, which operated for over a century. Spiritually, Kolar is home to Kotilingeshwara Temple in Kammasandra village, which houses a 108-foot-tall Lord Shiva Linga—one of the largest in the world—surrounded by nearly 10 million smaller Shiva Lingas donated by devotees. In Kolar town stand the 1,000-year-old Someshwara and Kolaramma Temples built during the Chola era.",
        season: "September to March",
        timings: "Kotilingeshwara Temple: 6:00 AM - 9:00 PM",
        fee: "Kotilingeshwara: ₹20 Entry",
        attractions: [
            "Kotilingeshwara Temple Complex (108-ft Shiva Linga)",
            "Kolaramma Temple & Someshwara Temple (Chola Architecture)",
            "Kolar Gold Fields (KGF) Historic Heritage Ruins",
            "Kurudumale Ganesha Temple (Monolithic Ganesha Shrine)",
            "Antaragange Hill (Gokarna Cave Temple & natural water spring)"
        ],
        reach: "Nearest Airport: Kempegowda International Airport (BLR, ~75 km). Highway: Located along the Bengaluru-Chennai Expressway (NH-75).",
        food: "Crispy South Indian Masala Dosa, Filter Coffee, Mysore Pak, and Fresh Dairy Sweets.",
        map: "https://maps.google.com/?q=Kotilingeshwara+Temple"
    },
    {
        id: "koppal",
        name: "Koppal",
        spot: "Anegundi & Mahadeva Temple Itagi",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The ancient Ramayana kingdom of Kishkindha at Anegundi and Western Chalukyan architectural gems.",
        overview: "Koppal district lies directly across the Tungabhadra River from Hampi. Anegundi, an ancient fortified town within Koppal, predates Hampi and is believed to be Kishkindha—the monkey kingdom described in the Ramayana epic. It features the Anjanadri Hill, believed to be the birthplace of Lord Hanuman. The district is also home to the Mahadeva Temple at Itagi, described in stone inscriptions as 'Devalaya Chakravarti' (Emperor among Temples), built by Western Chalukya king Vikramaditya VI in 1112 CE.",
        season: "October to March",
        timings: "6:00 AM - 6:00 PM",
        fee: "Free Entry",
        attractions: [
            "Anegundi Historic Village, Fort & Pampa Sarovar Lake",
            "Anjanadri Hill (Hanuman Birthplace Temple with 575 stone steps)",
            "Mahadeva Temple at Itagi (Western Chalukya masterpiece)",
            "Koppal Hill Fort Monolith",
            "Kuknoor Navalinga Temple Group"
        ],
        reach: "Rail: Koppal Railway Station (KBL) / Munirabad Station. Road: Connected via NH-67.",
        food: "Jolada Rotti, Sajje (Pearl Millet) Rotti, Badanekayi Curry, and Shenga Chutney.",
        map: "https://maps.google.com/?q=Anegundi+Karnataka"
    },
    {
        id: "mandya",
        name: "Mandya",
        spot: "Ranganathittu Bird Sanctuary & Srirangapatna",
        region: "South Interior",
        category: "Nature",
        image: "https://images.unsplash.com/photo-1561731216-c3a4d99437d5?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The sugar city of Karnataka, featuring riverine bird sanctuaries, island fortresses, and royal dams.",
        overview: "Mandya, fed by the Kaveri River, is an agricultural and historic district known as the 'Sugar Bowl of Karnataka.' It includes Srirangapatna, an island town in the Kaveri River that served as the capital of Hyder Ali and Tipu Sultan. Nearby lies Ranganathittu Bird Sanctuary, Karnataka's largest bird sanctuary, comprising six islets on the Kaveri River that host migratory species like painted storks, spoonbills, and mugger crocodiles. Mandya also features Krishna Raja Sagara (KRS) Dam and Brindavan Gardens.",
        season: "September to March (Best bird nesting season: June to November)",
        timings: "Ranganathittu: 8:30 AM - 5:40 PM | Brindavan Gardens: 10:00 AM - 8:00 PM",
        fee: "Ranganathittu: ₹70 Entry (+ Boat Ride charges)",
        attractions: [
            "Ranganathittu Bird Sanctuary (Guided Boat Tours)",
            "Srirangapatna Island Fort, Daria Daulat Bagh & Gumbaz",
            "Ranganathaswamy Temple at Srirangapatna",
            "Krishna Raja Sagara (KRS) Dam & Brindavan Gardens Fountains",
            "Shivanasamudra Falls (Gaganachukki & Bharachukki)",
            "Melukote Cheluvanarayana Swamy Temple & Academy of Sanskrit Research"
        ],
        reach: "Rail: Mandya Railway Station (MYA) / Srirangapatna Station on the Bengaluru-Mysuru line. Road: Located on the Bengaluru-Mysuru Expressway.",
        food: "Maddur Vada (Famous onion-rice flour fritters from Maddur), Ragi Mudde with Naati Koli Curry, and Sugarcane Juice.",
        map: "https://maps.google.com/?q=Ranganathittu+Bird+Sanctuary"
    },
    {
        id: "mysuru",
        name: "Mysuru (Mysore)",
        spot: "Mysore Palace & Chamundi Hill",
        region: "South Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1600100397608-f09070624022?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The Cultural Capital of Karnataka, world-renowned for Mysore Palace, royal Dasara processions, and silk.",
        overview: "Mysuru served as the capital of the Kingdom of Mysore from 1399 to 1947. The center of the city is the Mysore Palace (Amba Vilas), an Indo-Saracenic royal residence designed by British architect Henry Irwin, featuring carved mahogany ceilings, stained glass domes, and nearly 100,000 lightbulbs illuminated on weekends. Atop Chamundi Hill stands the 12th-century Chamundeshwari Temple overlooking the city. Mysuru is also famous worldwide for its 10-day Dasara festival.",
        season: "October to March (October for world-famous Mysore Dasara Festival)",
        timings: "Palace: 10:00 AM - 5:30 PM (Illumination on Sundays & Holidays: 7:00 PM - 8:00 PM)",
        fee: "Palace Entry: ₹100 for Indians, ₹300 for Foreigners",
        attractions: [
            "Mysore Palace (Amba Vilas Palace)",
            "Chamundeshwari Temple & Nandi Monolith on Chamundi Hill",
            "Sri Chamarajendra Zoological Gardens (Mysore Zoo)",
            "St. Philomena's Cathedral (Gothic Architecture Church)",
            "Jaganmohan Palace Art Gallery",
            "Karanji Lake & Butterfly Park"
        ],
        reach: "Airport: Mysore Airport (MYQ). Rail: Mysuru Junction (MYS). Highway: Connected via 10-lane Bengaluru-Mysuru Expressway.",
        food: "Mysore Pak (Ghee sweet), Mysore Masala Dosa, Churumuri, and Filter Coffee.",
        map: "https://maps.google.com/?q=Mysore+Palace"
    },
    {
        id: "raichur",
        name: "Raichur",
        spot: "Raichur Fort & Deosugur Temple",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "A historic fortress region sandwiched between the Krishna and Tungabhadra rivers.",
        overview: "Raichur district lies in the fertile Doab region between the Krishna and Tungabhadra rivers. Historically contested between the Kakatiyas, Vijayanagara Empire, and Bahmani Sultanate, Raichur Fort is renowned for its stone fortifications, including a 42-foot-long single stone slab with inscriptions in Persian and Telugu. Raichur is also a power-generation hub housing thermal power plants and the Raichur Thermal Power Station.",
        season: "October to March",
        timings: "8:00 AM - 6:00 PM",
        fee: "Free Entry",
        attractions: [
            "Raichur Fort & Sailani Darwaza Fort Gate",
            "Deosugur Sugureshwara Temple",
            "Mantra Kshethra Bichali (Tungabhadra riverfront shrine)",
            "Jaladurga Fort (Island fortress in Krishna River gorge)",
            "Gabbur Heritage Temple Village"
        ],
        reach: "Rail: Raichur Junction (RC) on the Guntakal-Solapur rail line. Road: Connected via State Highways.",
        food: "Jolada Rotti Meals, Shenga Pudi, and Spicy Mirchi Bajji.",
        map: "https://maps.google.com/?q=Raichur+Fort"
    },
    {
        id: "ramanagara",
        name: "Ramanagara",
        spot: "Ramadevara Betta & Janapada Loka",
        region: "South Interior",
        category: "Nature",
        image: "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The Silk City, surrounded by granite monoliths, vulture conservation sanctuaries, and folk art museums.",
        overview: "Ramanagara is famous as Karnataka's 'Silk City' due to its silk cocoon market—one of the largest in Asia. Surrounded by granite hills, it gained international fame as the shooting location for the classic Bollywood film 'Sholay' (Ramgarh). Ramadevara Betta in Ramanagara is India's only dedicated Vulture Sanctuary, protecting critically endangered Long-billed Vultures. The district also houses Janapada Loka, an open-air museum dedicated to preserving folk arts and culture.",
        season: "September to March",
        timings: "Ramadevara Betta: 9:00 AM - 4:30 PM | Janapada Loka: 9:00 AM - 5:30 PM",
        fee: "Ramadevara Betta: ₹25 Entry | Janapada Loka: ₹50 Entry",
        attractions: [
            "Ramadevara Betta Vulture Sanctuary & Hill Trek",
            "Janapada Loka Folk Art Open-Air Museum",
            "Kanva Reservoir & Camping Grounds",
            "Savandurga Hill (One of Asia's largest monolithic hills)",
            "Mekedatu Gorge & Sangama (Confluence of Kaveri & Arkavathi Rivers)"
        ],
        reach: "Nearest Airport: Bengaluru (75 km). Highway: Located directly along the Bengaluru-Mysuru Expressway.",
        food: "Maddur Vada, Thatte Idli, Ragi Mudde, and Mysore Pak.",
        map: "https://maps.google.com/?q=Ramadevara+Betta"
    },
    {
        id: "shivamogga",
        name: "Shivamogga (Shimoga)",
        spot: "Jog Falls & Agumbe Rainforest",
        region: "Malnad",
        category: "Nature",
        image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The Gateway to the Malnad region, featuring India's famous Jog Falls and dense tropical rainforests.",
        overview: "Shivamogga is blessed with rivers (Tunga, Bhadra, Sharavathi) and rainforests. It is home to Jog Falls—where the Sharavathi River drops 253 meters in four distinct cascades named Raja, Rani, Roarer, and Rocket. The district also contains Agumbe, often called the 'Cherrapunji of the South,' famous for its high rainfall, rainforest research station, king cobra habitat, and sunset views over the Arabian Sea.",
        season: "July to December (Monsoons for roaring waterfalls, winter for rainforest treks)",
        timings: "Jog Falls: 6:00 AM - 6:00 PM",
        fee: "Jog Falls: ₹15 Entry Fee + Vehicle Parking",
        attractions: [
            "Jog Waterfalls (253m plunge falls)",
            "Agumbe Rainforest Research Station & Sunset Viewpoint",
            "Sakrebyle Elephant Camp (Interactive elephant bathing on Tunga River)",
            "Mandagadde Bird Sanctuary",
            "Keladi & Ikkeri Historic Nayaka Dynasty Temples",
            "Kavaledurga Fort Hill Trek"
        ],
        reach: "Airport: Rashtrakuta Kuvempu Airport Shivamogga (RQY). Rail: Shivamogga Town Railway Station (SME).",
        food: "Malanadu Thali, Midigayi (Tender Mango) Pickles, Jackfruit Chips, and Halasina Hannina Kadabu.",
        map: "https://maps.google.com/?q=Jog+Falls"
    },
    {
        id: "tumakuru",
        name: "Tumakuru (Tumkur)",
        spot: "Devarayanadurga & Shivagange",
        region: "South Interior",
        category: "Pilgrimage",
        image: "https://images.unsplash.com/photo-1589182373726-e4f658ab50f0?auto=format&fit=crop&w=800&q=80",
        shortDesc: "An industrial and educational city surrounded by sacred hill ranges, natural springs, and temples.",
        overview: "Tumakuru is an industrial and educational center located northwest of Bengaluru. It is framed by sacred hill ranges like Devarayanadurga, a rocky hill station surrounded by forest that houses the Yoga Narasimha and Bhoga Narasimha temples at an altitude of 1,204 meters. Another major destination is Shivagange, a conical hill peak rising 1,368 meters that resembles a Shiva Linga, featuring natural springs like 'Olakal Teertha' and rock-cut shrines.",
        season: "October to March",
        timings: "6:00 AM - 7:00 PM",
        fee: "Free Entry",
        attractions: [
            "Devarayanadurga Hill Temples & Namada Chilume Spring",
            "Shivagange Hill Peak & Rock-cut Caves",
            "Siddaganga Matha (Renowned spiritual & educational institution)",
            "Siddara Betta (Medicinal herbs hill & cave temple)",
            "Yeddula Swamy Temple & Markonahalli Dam"
        ],
        reach: "Nearest Airport: Kempegowda International Airport (BLR, ~70 km). Rail: Tumakuru Railway Station (TK). Highway: NH-48.",
        food: "Tumakuru Thatte Idli (Plate-sized soft idlis served with spicy red chutney), Benne Dosa, and Filter Coffee.",
        map: "https://maps.google.com/?q=Devarayanadurga"
    },
    {
        id: "udupi",
        name: "Udupi",
        spot: "St. Mary's Island, Malpe Beach & Krishna Matha",
        region: "Coastal",
        category: "Beach",
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
        shortDesc: "Coastal destination famous for basalt rock islands, Malpe sea walk, and Sri Krishna Temple.",
        overview: "Udupi is world-famous for its temples, coastal beaches, and cuisine. The Sri Krishna Matha, founded in the 13th century by saint Madhvacharya, is unique because the deity is worshiped through a silver-plated window with nine holes ('Kanakana Kindi'). Geologically, Udupi features St. Mary's Island, accessible via boat from Malpe Beach, which showcases unique hexagonal columnar basaltic rock formations formed millions of years ago by volcanic activity.",
        season: "October to March (Island ferry closes during monsoons from June to September)",
        timings: "Krishna Matha: 5:00 AM - 9:00 PM | St. Mary's Ferry: 9:00 AM - 5:00 PM",
        fee: "Ferry to St. Mary's Island: ~₹400 per person round trip",
        attractions: [
            "St. Mary's Island (Hexagonal Columnar Basaltic Lava Rocks)",
            "Malpe Beach & Sea Walk Pier",
            "Udupi Sri Krishna Matha & Kanakana Kindi",
            "Kapu (Kaup) Beach & Historic 1901 Lighthouse",
            "Delta Beach (Kodi Bengre confluence of river and sea)",
            "Anegudde Vinayaka Temple Kumbhashi"
        ],
        reach: "Nearest Airport: Mangaluru International Airport (IXE, ~60 km). Rail: Udupi Railway Station (UD) on the scenic Konkan Railway.",
        food: "Udupi Masala Dosa, Neer Dosa, Goli Baje, Gadbad Ice Cream, and coastal Fish Curry.",
        map: "https://maps.google.com/?q=St+Marys+Island+Udupi"
    },
    {
        id: "uttara-kannada",
        name: "Uttara Kannada (Karwar)",
        spot: "Gokarna Om Beach, Murudeshwar & Dandeli",
        region: "Coastal",
        category: "Beach",
        image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80",
        shortDesc: "A district offering Gokarna beach treks, Murudeshwar's Shiva statue, and river rafting in Dandeli.",
        overview: "Uttara Kannada boasts a long coastline and forest cover. Gokarna is famous for its Om Beach (shaped like the sacred 'Om' symbol) and beach trekking routes. Murudeshwar features the world's second-tallest Shiva statue (123 feet) and a 20-story Gopuram towering over the Arabian Sea. Inland, Dandeli offers white-water rafting on the Kali River and dense wildlife reserves.",
        season: "October to March",
        timings: "Open 24 Hours (Beaches & Murudeshwar Temple Complex)",
        fee: "Free Entry across beaches",
        attractions: [
            "Gokarna Om Beach, Kudle Beach & Mahabaleshwar Temple",
            "Murudeshwar Shiva Statue & Raja Gopuram",
            "Dandeli Wildlife Sanctuary & Kali River White-Water Rafting",
            "Yana Black Crystalline Monolith Rocks & Caves",
            "Mirjan Fort (16th-century pepper queen fort)",
            "Supa Dam & Backwaters"
        ],
        reach: "Airport: Goa Dabolim Airport (GOI, ~140 km from Karwar). Rail: Gokarna Road (GOK), Karwar (KAWR), and Murdeshwar (MRDW) on the Konkan Railway.",
        food: "Karwar Fish Curry with Rice, Banana Pancakes, Clam Sukka, and Sol Kadi.",
        map: "https://maps.google.com/?q=Om+Beach+Gokarna"
    },
    {
        id: "vijayanagara",
        name: "Vijayanagara",
        spot: "Hampi UNESCO World Heritage Site",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The capital of the Vijayanagara Empire, featuring stone chariots, royal baths, and boulder landscapes.",
        overview: "Carved out of Ballari district in 2021, Vijayanagara is named after its crown jewel: Hampi, a UNESCO World Heritage site that served as the capital of the Vijayanagara Empire during the 14th–16th centuries. Set along the Tungabhadra River among giant boulder hills, Hampi contains over 1,600 surviving monuments. Key sites include the Vittala Temple complex with its stone chariot and musical pillars, the active Virupaksha Temple, Lotus Mahal, and the Elephant Stables.",
        season: "November to February (Hampi Utsav cultural festival in November/February)",
        timings: "Vittala Temple & Royal Enclosure: 8:30 AM - 5:30 PM",
        fee: "₹40 for Indians, ₹600 for Foreigners (Covers main ticketed monument group)",
        attractions: [
            "Vittala Temple & Iconic Monolithic Stone Chariot",
            "Virupaksha Temple (Active 7th-century shrine with 160-ft Gopuram)",
            "Lotus Mahal & Elephant Stables inside Royal Enclosure",
            "Ugra Narasimha & Badavilinga Monoliths",
            "Matanga Hill & Hemakuta Hill Sunset Viewpoints",
            "Tungabhadra Dam & Gardens at Hospet"
        ],
        reach: "Rail: Hospet Junction (HPT) is just 13 km from Hampi. Airport: Jindal Vijaynagar Airport (VDY, ~35 km).",
        food: "South Indian Thali, Fresh Coconut Water, Herbal Teas, and Multi-Cuisine options in Hampi's Bazaar.",
        map: "https://maps.google.com/?q=Hampi+Karnataka"
    },
    {
        id: "vijayapura",
        name: "Vijayapura (Bijapur)",
        spot: "Gol Gumbaz & Ibrahim Rauza",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "The Deccan Sultanate capital famous for the world's second-largest dome and its acoustic Whispering Gallery.",
        overview: "Vijayapura served as the capital of the Adil Shahi dynasty (1489–1686). The city is dominated by Gol Gumbaz, the mausoleum of Mohammed Adil Shah. Completed in 1656, its central dome is the second-largest in the world (44 meters in diameter) constructed without external pillar support. Inside the dome lies the 'Whispering Gallery,' where the softest sound echoes 11 times. Another key attraction is Ibrahim Rauza, often termed the 'Taj Mahal of the Deccan.'",
        season: "October to March",
        timings: "Gol Gumbaz: 6:00 AM - 6:00 PM",
        fee: "₹25 for Indians, ₹300 for Foreigners",
        attractions: [
            "Gol Gumbaz & Acoustic Whispering Gallery",
            "Ibrahim Rauza (Palatial tomb complex built by Ibrahim Adil Shah II)",
            "Jama Masjid Bijapur (Sprawling 16th-century congregational mosque)",
            "Bara Kaman (Unfinished 12-arch mausoleum)",
            "Malik-e-Maidan (The legendary 55-ton bronze cannon)"
        ],
        reach: "Airport: Kalaburagi Airport (110 km) / Solapur Airport (100 km). Rail: Vijayapura Railway Station (BJP).",
        food: "Jolada Rotti Oota, Shenga Chutney, Badanekayi Yennegai, and Bijuri Sweets.",
        map: "https://maps.google.com/?q=Gol+Gumbaz+Bijapur"
    },
    {
        id: "yadgir",
        name: "Yadgir",
        spot: "Yadgir Fort & Sleeping Buddha Hill",
        region: "North Interior",
        category: "Heritage",
        image: "https://images.unsplash.com/photo-1620766182966-c6eb5ed2b788?auto=format&fit=crop&w=800&q=80",
        shortDesc: "A hill fort region featuring a monolithic boulder citadel and hill ranges shaped like a resting Buddha.",
        overview: "Yadgir district, carved out of Kalaburagi in 2010, is rich in historical fortifications along the Bhima and Krishna rivers. Yadgir town features a hill fort constructed atop a massive single-boulder hill by the Western Chalukya dynasty and later expanded under the Bahmani and Adil Shahi rulers, containing historic cannons and water tanks. In Shahapur town, the natural outline of the surrounding hill ranges uniquely resembles a reclining 'Sleeping Buddha.'",
        season: "October to March",
        timings: "8:00 AM - 5:00 PM",
        fee: "Free Entry",
        attractions: [
            "Yadgir Hill Fort Monolith & Historic Cannons",
            "Sleeping Buddha Hill Range in Shahapur",
            "Shorapur Fort & Royal Palace (Surpur Nayaka kingdom history)",
            "Chintanalli Gavisiddeshwara Temple Cave",
            "Narayanpur Dam across Krishna River"
        ],
        reach: "Rail: Yadgir Railway Station (YG) on the Mumbai-Chennai main railway trunk line. Road: Connected via State Highways.",
        food: "Authentic North Karnataka Jolada Rotti, Shenga Pudi, Badanekayi Curry, and Puffed Rice Snacks.",
        map: "https://maps.google.com/?q=Yadgir+Fort"
    }
];
